### ISSUE TITLE
无法编译超过 73 个 block

### ISSUE THREAD

**Issue by ambar** [tinajs/mina-webpack#12]
如果每个文件 3 个 block（config/style/template），约 25 个 mina 文件就会直接程序挂掉，毫无错误提示。暂时不知道是 webpack 本身问题还是其他。

**Comment by imyelo** [comment]
巧了，刚好今天也在排查这个问题

**Comment by imyelo** [comment]
找到了大致的原因。

简单的处理方式是：

在 webpack.config(.babel).js 中添加配置：

```
parallelism: 150,
```

或者也可以是更大的数值。
该选项 [默认值是 100](https://github.com/webpack/webpack/blob/949890acdf1d00d9e53054b56ad3e7215215416d/lib/Compilation.js#L237)，而当 mina-loader 并发调用了超过 100 次 loadModule 之后出现了异常，可以根据文件数适量加大这个值。

具体原因还没查明白。怀疑和这个 [PR](https://github.com/webpack/webpack/issues/6836) 有关系。

**Comment by imyelo** [comment]
@huanghui1 直接 parse 的话是指？

**Comment by huanghui1** [comment]
https://github.com/tinajs/mina-webpack/blob/master/packages/mina-loader/lib/loaders/parser.js#L3

就是直接`export parser`，调用`parser`，没有试过不知道行不行:joy:

**Comment by malash** [comment]
I also meet this issue and make a demo to reproduce the bug :

https://github.com/malash/mina-webpack/blob/issue/example/src/pages/test.mina

Increasing `parallelism` helped but can we solve the problem fundamentally ?

**Comment by imyelo** [comment]
The root cause of the problem is this:
- https://github.com/webpack/webpack/issues/6836

And I think the version that webpack resolved for this bug is 4.6.0:
- https://github.com/webpack/webpack/pull/7027
- https://github.com/webpack/webpack/commit/40a089c98cff6c8d5af65aa8ed35f87f27d081dd
- https://github.com/webpack/webpack/releases/tag/v4.6.0 

Unfortunately, currently mina-webpack only supports webpack 3, so for the time being we can only increase the value of the `parallelism` to avoid this problem. 

This issue will remain open until we support webpack 4. Very sorry for the inconvenience.

**Comment by Jimexist** [comment]
@imyelo this should be closed?

**Comment by imyelo** [comment]
@Jimexist This will be closed after release v1.0.0

**Comment by jeffwcx** [comment]
就在刚刚碰到这个问题，好在已经有人发现了，不然就完蛋了
